#---------------------------------------------------------------#
#------------------------- Ops Resources -----------------------#
#---------------------------------------------------------------#

resources:
#################################################################
## Shared resources
# Automation scripts repo
  - name: infra_repo
    type: gitRepo
    integration: demo_github
    versionTemplate:
      sourceName: "aye0aye/ops"
      branch: master

##################################################################
#### AWS Provisioning Resources
# TEST AWS cluster
  - name: test_env_ecs
    type: cluster
    integration: demo_aws # replace with your AWS integration name
    versionTemplate:
      # replace with your Amazon ECS cluster name and region
      sourceName : ${CLUSTER_NAME}
      region: ${REGION}

## TEST AWS ALB target group
#  - name: test_alb     #required
#    type: loadBalancer #required
#    versionTemplate:
#      # replace with the ARN for your Amazon EC/2 Application Load Balancer Target Group
#      sourceName: "arn:aws:elasticloadbalancing:us-east-1:679404489841:targetgroup/ecs-test-tg/bc20de1be2dab77d"
#      method: application

# TEST environment config
  - name: test_env_conf_ans
    type: params
    versionTemplate:
      params:
        EC2_TAG_ROLE: "test_env_demo"
        EC2_TAG_TYPE: "ecs_container_instance"
        VPC_KEYPAIR_NAME: "demo_us_east_1"
        ECS_AMI: "ami-ba722dc0"
        EC2_COUNT: 2
        EC2_INSTANCE_TYPE: "t2.micro"
        ECS_CLUSTER_NAME: "test_env_demo"
        ENVIRONMENT: "test"

# PROD AWS cluster
  - name: prod_env_ecs
    type: cluster
    integration: demo_aws # replace with your AWS integration name
    versionTemplate:
      # replace with your Amazon ECS cluster name and region
      sourceName : ${CLUSTER_NAME}
      region: ${REGION}

## PROD AWS ALB target group
#  - name: prod_alb     #required
#    type: loadBalancer #required
#    versionTemplate:
#      # replace with the ARN for your Amazon EC/2 Application Load Balancer Target Group
#      sourceName: "arn:aws:elasticloadbalancing:us-east-1:679404489841:targetgroup/ecs-test-tg/bc20de1be2dab77d"
#      method: application

# PROD environment config
  - name: prod_env_conf_ans
    type: params
    versionTemplate:
      params:
        EC2_TAG_ROLE: "prod_env_demo"
        EC2_TAG_TYPE: "ecs_container_instance"
        VPC_KEYPAIR_NAME: "demo_us_east_1"
        ECS_AMI: "ami-ba722dc0"
        EC2_COUNT: 2
        EC2_INSTANCE_TYPE: "t2.micro"
        ECS_CLUSTER_NAME: "prod_env_demo"
        ENVIRONMENT: "prod"

##################################################################
#### Kubernetes cluster on AWS resources
#
## Kubernetes cluster on AWS for use with managed Deploy job
#  - name: e2eshipdemo-cluster-kube
#    type: cluster
#    integration: ttrahan-kube # replace with your Kube integration name
#    pointer:
#      # replace with your Kubernetes cluster name and region
#      sourceName : "cluster"
#      region: "us-east-1"
#    flags:
#      - e2eShippableDemo
#      - kubernetes
#
## AWS CLI config - kops
#  - name: aws_cli_config_kube
#    type: cliConfig
#    integration: dr-aws-kops
#    pointer:
#      region: us-east-1
#    flags:
#      - e2eShippableDemo
#      - kubernetes
#
## SSH keys for use in KOPS provisioning
#  - name: sshkey_kops
#    type: integration
#    integration: kp-us-east-1-kops
#    flags:
#      - e2eShippableDemo
#      - kubernetes
#
## Kube cluster config
#  - name: kube_cluster_config
#    type: params
#    version:
#      params:
#        CLUSTER_NAME: "cluster.prod.example-kube-cluster.com"
#        KOPS_STATE_STORE: "s3://kube-cluster-state"
#        CLOUD: "aws"
#        ZONES: "us-east-1c"
#        MASTER_ZONES: "us-east-1c"
#        MASTER_SIZE: "m3.medium"
#        NODE_SIZE: "t2.medium"
#        NODE_COUNT: 2
#    flags:
#      - e2eShippableDemo
#      - kubernetes
#
## Kube cluster info
#  - name: kube_cluster_info
#    type: params
#    version:
#      params:
#        SEED: "initial placeholder"
#    flags:
#      - e2eShippableDemo
#      - kubernetes
#
##################################################################
#### Google Cloud - Devops Recipes account
#
## GKE cluster
#  - name: gke_cluster
#    type: cluster
#    integration: drship_gke    #replace with your Kubernetes integration name
#    pointer:
#      sourceName: "shipdemo-cluster"
#      namespace: devops-samples
#      region: us-central1-b
#

## PROD replicas
#  - name: e2eshipdemo-replicas-ecs-prod
#    type: replicas
#    version:
#      count: 2
#    flags:
#      - e2eShippableDemo


#---------------------------------------------------------------#
#--------------------------- Ops Jobs --------------------------#
#---------------------------------------------------------------#
jobs:
# Provision TEST VMs and ECS cluster with Ansible
  - name: prov_test_env_ans
    type: runSh
    dependencyMode: strict
    triggerMode: parallel
    steps:
      - IN: ami_secops_approved
      - IN: demo_aws_cli
        switch: off
      - IN: test_env_conf_ans
        switch: off
      - IN: demo_aws_pem
        switch: off
      - IN: test_vpc_info
        switch: off
      - IN: infra_repo
        switch: off
      - TASK:
          script:
            - sudo pip install boto3
            - pushd $(shipctl get_resource_state "infra_repo")
            - cd ./infra/provision-ecs-ansible
            - export CLUSTER_RES_NAME="test_env_ecs"
            - export AMI_ID=$(shipctl get_resource_version_name ami_secops_approved)
            - export PUBLIC_SN_01_ID=$TEST_PUBLIC_SN_01_ID
            - export PUBLIC_SN_02_ID=$TEST_PUBLIC_SN_02_ID
            - export PUBLIC_SG_ID=$TEST_PUBLIC_SG_ID
            - shipctl replace ansible.cfg ./group_vars/ecs-cluster-vars.yml
            - ansible-playbook -v ansible-ecs-provision.yml
            - popd
      - OUT: test_env_ecs
        overwrite: true
    flags:
      - e2e_demo_app

# Deprovision TEST VMs and ECS cluster
  - name: deprov_test_env_ans
    type: runSh
    steps:
      # - IN: auto_bvt
      #   switch: off
      - IN: prov_test_env_ans
        switch: off
      - IN: demo_aws_cli
        switch: off
      - IN: test_env_conf_ans
        switch: off
      - IN: test_vpc_info
        switch: off
      - IN: demo_aws_pem
        switch: off
      - IN: infra_repo
        switch: off
      - IN: ami_secops_approved
        switch: off
      - TASK:
          script:
            - sudo pip install boto3
            - pushd $(shipctl get_resource_state "infra_repo")
            - cd ./infra/provision-ecs-ansible
            - export CLUSTER_RES_NAME="test_env_ecs"
            - export AMI_ID=$(shipctl get_resource_version_name ami_secops_approved)
            - export PUBLIC_SN_01_ID=$PROD_PUBLIC_SN_01_ID
            - export PUBLIC_SN_02_ID=$PROD_PUBLIC_SN_02_ID
            - export PUBLIC_SG_ID=$PROD_PUBLIC_SG_ID
            - shipctl replace ansible.cfg group_vars/ecs-cluster-vars.yml
            - ansible-playbook -v ansible-ecs-terminate.yml
            - popd
      - OUT: test_env_ecs
        overwrite: true
    flags:
      - e2e_demo_app

# Provision PROD VMs and ECS cluster with Ansible
  - name: prov_prod_env_ans
    type: runSh
    dependencyMode: strict
    triggerMode: parallel
    steps:
      - IN: ami_secops_approved
      - IN: demo_aws_cli
        switch: off
      - IN: prod_env_conf_ans
        switch: off
      - IN: demo_aws_pem
        switch: off
      - IN: prod_vpc_info
        switch: off
      - IN: infra_repo
        switch: off
      - TASK:
          script:
            - sudo pip install boto3
            - pushd $(shipctl get_resource_state "infra_repo")
            - cd ./infra/provision-ecs-ansible
            - export CLUSTER_RES_NAME="prod_env_ecs"
            - export AMI_ID=$(shipctl get_resource_version_name ami_secops_approved)
            - shipctl replace ansible.cfg ./group_vars/ecs-cluster-vars.yml
            - ansible-playbook -v ansible-ecs-provision.yml
            - popd
      - OUT: prod_env_ecs
        overwrite: true
    flags:
      - e2e_demo_app

# Deprovision PROD VMs and ECS cluster
  - name: deprov_prod_env_ans
    type: runSh
    steps:
      - IN: prov_prod_env_ans
        switch: off
      - IN: demo_aws_cli
        switch: off
      - IN: prod_env_conf_ans
        switch: off
      - IN: prod_vpc_info
        switch: off
      - IN: demo_aws_pem
        switch: off
      - IN: infra_repo
        switch: off
      - IN: ami_secops_approved
        switch: off
      - TASK:
          script:
            - sudo pip install boto3
            - pushd $(shipctl get_resource_state "infra_repo")
            - cd ./infra/provision-ecs-ansible
            - export CLUSTER_RES_NAME="prod_env_ecs"
            - export AMI_ID=$(shipctl get_resource_version_name ami_secops_approved)
            - shipctl replace ansible.cfg group_vars/ecs-cluster-vars.yml
            - ansible-playbook -v ansible-ecs-terminate.yml
            - popd
      - OUT: prod_env_ecs
        overwrite: true
    flags:
      - e2e_demo_app

#
## Provision Kubernetes cluster with KOPS
#  - name: prov_kube_cluster
#    type: runSh
#    steps:
#      - IN: aws_cli_config_kube
#        switch: off
#      - IN: sshkey_kops
#        switch: off
#      - IN: prod_vpc_conf
#        switch: off
#      - IN: ops_repo
#        switch: off
#      - IN: kube_cluster_config
#        switch: off
#      - OUT: kube_cluster_info
#      - TASK:
#        # install KOPS CLI
#        - script: |
#            wget -q -O kops https://github.com/kubernetes/kops/releases/download/1.7.0/kops-linux-amd64
#            chmod +x ./kops
#            sudo mv ./kops /usr/local/bin
#        # set aws variables for use by KOPS
#        - script: |
#            export AWS_ACCESS_KEY_ID=$(aws configure get aws_access_key_id)
#            export AWS_SECRET_ACCESS_KEY=$(aws configure get aws_secret_access_key)
#        # create Kubernetes cluster
#        - script: echo "---creating cluster---"
#          # update cluster spec with input parameters
#        - script: |
#            pushd ${OPS_REPO_STATE}/infra/provision-kube-kops
#            shipctl replace kube-cluster.yaml
#            cat kube-cluster.yaml
#          # check if cluster exist, create if not, replace otherwise
#        - script: |
#            if [[ ! $(kops get cluster --name "${CLUSTER_NAME}") ]]; then
#              echo "creating cluster"
#              kops create -f kube-cluster.yaml --name "${CLUSTER_NAME}"
#              kops create secret --name ${CLUSTER_NAME} sshpublickey admin -i $SSHKEY_KOPS_PUBLIC_KEY_PATH
#              echo "done creating cluster"
#            else
#              echo "replacing cluster"
#              kops replace -f kube-cluster.yaml --name "${CLUSTER_NAME}"
#              echo "done replacing cluster"
#            fi
#            popd
#          # provision Kubernetes cluster
#        - script: |
#            echo "---provisioning cluster---"
#            kops update cluster $CLUSTER_NAME --yes --state $KOPS_STATE_STORE --yes
#            echo "---cluster provisioning triggered---"
#          # save cluster info to state
#        - script: >
#            shipctl put_resource_state kube_cluster_info
#            CLUSTER_NAME ${CLUSTER_NAME}
#            KOPS_STATE_STORE ${KOPS_STATE_STORE}
#            CLOUD ${CLOUD}
#            MASTER_LOCATION ${MASTER_ZONES}
#    on_success:
#      - script: echo "SUCCESS"
#    on_failure:
#      - script: echo "FAILURE"
#    flags:
#      - e2eShippableDemo
#      - kubernetes
#
## Deprovision Kubernetes cluster with KOPS
#  - name: deprov_kube_cluster
#    type: runSh
#    steps:
#      - IN: prov_kube_cluster
#        switch: off
#      - IN: aws_cli_config_kube
#        switch: off
#      - IN: kube_cluster_config
#        switch: off
#      - TASK:
#        # install KOPS CLI
#        - script: |
#            wget -q -O kops https://github.com/kubernetes/kops/releases/download/1.7.0/kops-linux-amd64
#            chmod +x ./kops
#            sudo mv ./kops /usr/local/bin
#        # set aws variables for use by KOPS
#        - script: |
#            export AWS_ACCESS_KEY_ID=$(aws configure get aws_access_key_id)
#            export AWS_SECRET_ACCESS_KEY=$(aws configure get aws_secret_access_key)
#        # deprovision Kubernetes cluster
#        - script: echo "---deprovisioning cluster---"
#        - script: kops delete cluster $CLUSTER_NAME --yes --state $KOPS_STATE_STORE --yes
#        - script: echo "---cluster deprovisioning triggered---"
#    on_success:
#      - script: echo "SUCCESS"
#    on_failure:
#      - script: echo "FAILURE"
#    flags:
#      - e2eShippableDemo
#      - kubernetes


#
## PROD deployment to Amazon ECS
#  - name: e2eshipdemo-deploy-ecs-prod
#    type: deploy
#    steps:
#      - IN: e2eshipdemo-release-ecs-prod
#        switch: off
#      - IN: e2eshipdemo-params-ecs-prod
#      - IN: e2eshipdemo-img-options-ecs-prod
#      - IN: e2eshipdemo-replicas-ecs-prod
#      - IN: e2eshipdemo-cluster-ecs-prod
#      - IN: e2eshipdemo-alb-prod
#        applyTo:
#          - manifest: e2eshipdemo-manifest-ecs
#            image: e2eshipdemo-img-ecs
#            port: 80
#      - TASK: managed
#        # deployMethod: replace
#    flags:
#      - e2eShippableDemo
#      - ecs
#